services:
  app:
    build: .
    container_name: thread-wallet-app
    ports:
      - "8080:8080"
    networks:
      - wallet-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://wallet-db:5432/walletDb
      - SPRING_DATASOURCE_USERNAME=usuario
      - SPRING_DATASOURCE_PASSWORD=senha_forte

networks:
  wallet-network:
    external: true