# Datasource (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/walletDb
spring.datasource.username=usuario
spring.datasource.password=senha_forte
spring.datasource.driver-class-name=org.postgresql.Driver