CREATE TABLE IF NOT EXISTS carteira (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_cliente VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ativo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carteira_id BIGINT NOT NULL,
    ticker VARCHAR(255) NOT NULL,
    valor_atual FLOAT(53) NOT NULL,
    taxa_volatilidade FLOAT(53) NOT NULL,
    CONSTRAINT fk_ativo_carteira FOREIGN KEY (carteira_id) REFERENCES carteira(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_ativo_carteira_id ON ativo(carteira_id);

CREATE TABLE IF NOT EXISTS risco_calculado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carteira_id BIGINT NOT NULL,
    valor FLOAT(53) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    CONSTRAINT fk_risco_carteira FOREIGN KEY (carteira_id) REFERENCES carteira(id) ON DELETE CASCADE,
    CONSTRAINT uk_risco_carteira_tipo UNIQUE (carteira_id, tipo)
);

CREATE INDEX IF NOT EXISTS idx_risco_calculado_carteira_id ON risco_calculado(carteira_id);
