CREATE TABLE IF NOT EXISTS carteira (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_cliente VARCHAR(255) NOT NULL,
    risco_calculado FLOAT(53)
);

CREATE TABLE IF NOT EXISTS ativo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carteira_id BIGINT NOT NULL,
    ticker VARCHAR(255) NOT NULL,
    valor_atual FLOAT(53) NOT NULL,
    taxa_volatilidade FLOAT(53) NOT NULL,
    CONSTRAINT fk_ativo_carteira FOREIGN KEY (carteira_id) REFERENCES carteira(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_ativo_carteira_id ON ativo(carteira_id);
